### ISSUE TITLE
application crash when MPI_alltoallw() wrapped by APMPI uses the MPI_DATATYPE_NULL type

### ISSUE THREAD

**Issue by carns** [argonne-lcf/autoperf#13]
See https://github.com/darshan-hpc/darshan/issues/698 for context from @bebosudo  and @jedwards4b. This was originally filed on Darshan, but the problem is actually being encountered in the AutoPerf APMPI module in Darshan.

The underlying issue is that some MPI implementations may crash (or more pedantically, throw an unhandled error) if MPI_Type_size() is called on MPI_DATATYPE_NULL.  The MPI spec doesn't specify what is supposed to happen in this case.  AutoPerf and Darshan both issue MPI_Type_size() calls without the application's knowledge, and may therefore introduce unexpected application errors.

Since there are MPI libraries in production that do this, the safest solution is to wrap calls to MPI_Type_size() in the APMPI wrappers with guards (maybe in a macro) that catches the MPI_DATATYPE_NULL case and either replaces it with a safe type or just sets the size to 0.  This is especially important for application codes that are already going out of their way to avoid passing MPI_DATATYPE_NULL into particular function calls but don't realize that autoperf may trigger additional MPI calls as part of its instrumentation.

Once we confirm a fix here, then the same fix can probably be applied in Darshan's core MPIIO module.  The similar hypothetical problem in the MPIIO module can't be triggered right now as best I can tell, but it could be in the future if an MPI library behaved slightly differently.

Here is a single process reproducer that works on both Cori with its default user environment as well as on my laptop with MPICH 3.4.1 and Darshan origin/main with --enable-apmpi-mod:

```
#include <stdio.h>
#include <mpi.h>

int main(int argc, char* argv[])
{
    int          ret;
    int          sendcounts[1] = {0};
    int          sdispls[1]    = {0};
    int          recvcounts[1] = {0};
    int          rdispls[1]    = {0};
    char         rbuffer[1]    = {0};
    char         sbuffer[1]    = {0};
    MPI_Datatype sendtypes[1]  = {MPI_DATATYPE_NULL};
    MPI_Datatype recvtypes[1]  = {MPI_DATATYPE_NULL};
    int          nprocs        = 0;

    MPI_Init(&argc, &argv);

    MPI_Comm_size(MPI_COMM_WORLD, &nprocs);

    if (nprocs != 1) {
        fprintf(stderr,
                "Error: this test program must be executed with exactly one "
                "process.\n");
        return (-1);
    }

#if 0
    MPI_Errhandler_set(MPI_COMM_WORLD,MPI_ERRORS_RETURN);
#endif

    ret = MPI_Alltoallw(sbuffer, sendcounts, sdispls, sendtypes, rbuffer,
                        recvcounts, rdispls, recvtypes, MPI_COMM_WORLD);

    if (ret != MPI_SUCCESS)
        fprintf(stderr, "Error: MPI_Alltoallw(); continuing...\n");

    MPI_Finalize();
    return 0;
}
```
The desired behavior is for it to execute without crashing.

**Comment by shanedsnyder** [comment]
@sudheer9 -- any chance you could have a look at this sometime in the next couple of weeks? We'd like to include a fix for this in Darshan 3.4.0 if possible.
